<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="0" failures="2" skipped="1" tests="5" time="0.033" timestamp="2025-08-19T17:30:01.667111+00:00" hostname="codespaces-a0f17d"><testcase classname="testreports.tests.test_sample" name="test_TC001" time="0.000" /><testcase classname="testreports.tests.test_sample" name="test_TC002" time="0.000" /><testcase classname="testreports.tests.test_sample" name="test_TC003" time="0.001"><failure message="assert (1 + 1) == 3">def test_TC003():
&gt;       assert 1 + 1 == 3  # わざと失敗
        ^^^^^^^^^^^^^^^^^
E       assert (1 + 1) == 3

tests/test_sample.py:12: AssertionError</failure></testcase><testcase classname="testreports.tests.test_sample" name="test_TC004" time="0.001"><failure message="assert (1 + 2) == 4">def test_TC004():
&gt;       assert 1 + 2 == 4  # わざと失敗
        ^^^^^^^^^^^^^^^^^
E       assert (1 + 2) == 4

tests/test_sample.py:15: AssertionError</failure></testcase><testcase classname="testreports.tests.test_sample" name="test_TC005" time="0.000"><skipped type="pytest.skip" message="デモ用にスキップ">/workspaces/sn-study/testreports/tests/test_sample.py:17: デモ用にスキップ</skipped></testcase></testsuite></testsuites>